<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="FluentValidation.AspNetCore" Version="11.3.1" />
    <PackageVersion Include="Microsoft.AspNetCore.Authentication.OpenIdConnect" Version="8.0.11" />
    <PackageVersion Include="Microsoft.EntityFrameworkCore" Version="8.0.13" />
    <PackageVersion Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.13" />
    <PackageVersion Include="Microsoft.EntityFrameworkCore.SqlServer" Version="8.0.13" />
    <PackageVersion Include="Microsoft.EntityFrameworkCore.Tools" Version="8.0.13" />
    <PackageVersion Include="Microsoft.EntityFrameworkCore.Relational" Version="8.0.13" />
    <PackageVersion Include="Microsoft.AspNetCore.DataProtection.EntityFrameworkCore" Version="8.0.13" />
    <PackageVersion Include="Pomelo.EntityFrameworkCore.MySql" Version="8.0.3" />
    <PackageVersion Include="Microsoft.Extensions.Caching.SqlServer" Version="8.0.13" />
    <PackageVersion Include="Microsoft.Extensions.Logging.Abstractions" Version="10.0.0" />
    <PackageVersion Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="10.0.0" />
    <PackageVersion Include="Microsoft.Extensions.Hosting.Abstractions" Version="8.0.0" />
    <PackageVersion Include="Microsoft.Extensions.Caching.Abstractions" Version="8.0.0" />
    <PackageVersion Include="Pomelo.Extensions.Caching.MySql" Version="2.2.1" />
    <PackageVersion Include="EPPlus" Version="8.4.1" />
    <PackageVersion Include="Newtonsoft.Json" Version="13.0.3" />
    <PackageVersion Include="AutoMapper" Version="16.1.1" />
    <PackageVersion Include="FluentValidation" Version="11.5.1" />
    <PackageVersion Include="Microsoft.AspNetCore.Http.Abstractions" Version="2.3.0" />
    <PackageVersion Include="ClosedXML" Version="0.105.0" />
    <PackageVersion Include="JW.Pager" Version="1.0.1" />
    <PackageVersion Include="RestSharp" Version="114.0.0" />
    <PackageVersion Include="Serilog" Version="4.3.0" />
    <PackageVersion Include="Serilog.AspNetCore" Version="8.0.3" />
    <PackageVersion Include="TwoFactorAuth.Net" Version="1.4.0" />
	<PackageVersion Include="Microsoft.Extensions.Diagnostics.HealthChecks.EntityFrameworkCore" Version="8.0.13" />
	<PackageVersion Include="FluentAssertions" Version="6.12.0" />
	<PackageVersion Include="Microsoft.NET.Test.Sdk" Version="17.12.0" />
	<PackageVersion Include="xunit" Version="2.9.2" />
	<PackageVersion Include="xunit.runner.visualstudio" Version="2.8.2" />
	<PackageVersion Include="Testcontainers" Version="3.10.0" />
	<PackageVersion Include="Testcontainers.MsSql" Version="3.10.0" />
	<PackageVersion Include="Testcontainers.MySql" Version="3.10.0" />
	<PackageVersion Include="NSubstitute" Version="5.1.0" />
  </ItemGroup>
</Project>